services:
  paddock-api:
    container_name: paddock-api
    image: ghcr.io/drumandbytes/paddock-api:latest
    environment:
      - TIMEZONE=America/Edmonton
      - TRACK_COLOUR=#e5d486
      - EVENT_DETAIL=main
    ports:
      - 4463:4463
    restart: unless-stopped
